// Auto-generated by scripts/generate-optimized.cjs - do not edit
export type OptimizedEntry = { avif?: string; webp?: string; fallback?: string; lqip?: string };
const manifest: Record<string, OptimizedEntry> = {
  "_optimized": {}
} as any;

export default manifest;

export function pickOptimized(key: string): OptimizedEntry | null {
  return (manifest as any)[key] || null;
}
