#!/usr/bin/env bash
set -euo pipefail

REPO="$HOME/Documents/Development/Gorstan"
IMG="$REPO/public/images"
ARCHIVE="$IMG/_archive/replaced-by-revised-room-images"
MANIFEST="$REPO/docs/visuals/ARCHIVED_REPLACED_ROOM_IMAGES.md"

DRY_RUN="${DRY_RUN:-1}"

mkdir -p "$ARCHIVE" "$REPO/docs/visuals"

# old_file|new_replacement|reason
REPLACEMENTS=$(cat <<'MAP'
elfhameZone_elfhame.png|elfhame_hub.png|Replaced by revised Elfhame hub image
elfhameZone_faeglade.png|elfhame_woods.png|Replaced by revised Elfhame woods image
elfhameZone_faelakenorthshore.png|elhame_lake.png|Likely replaced by revised lake image; note filename is elhame_lake
elfhameZone_faelake.png|elhame_lake.png|Likely replaced by revised lake image; note filename is elhame_lake
elfhameZone_faepalace.png|elfhame_palace.png|Replaced by revised Elfhame palace image
glitchrealm_glitchrealmhub.png|glitch_hub.png|Replaced by revised Glitch hub image
glitchZone_glitchinguniverse.png|glitch_hub.png|Likely replaced by revised Glitch hub image
gorstanZone_carronspire.png|gorstan_carronspire.png|Replaced by revised Carron Spire image
gorstanZone_gorstanhub.png|gorstan_hub.png|Replaced by revised Gorstan hub image
gorstanZone_torridon.png|gorstan_torridon.png|Replaced by revised Torridon image
gorstanZone_torridonbefore.png|gorstan_torridon_ruined.png|Likely replaced by revised ruined Torridon image
gorstanZone_torridoninn.png|gorstan_torridon_inn.png|Replaced by revised Torridon Inn image
introZone_introreset.png|introzone_introreset.png|Replaced by canonical lowercase intro reset image
introZone_resetroom.png|introzone_introreset.png|Likely replaced by revised intro reset image
latticehub.png|lattice_hub.png|Replaced by revised lattice hub image
latticeZone_hub.png|lattice_hub.png|Replaced by revised lattice hub image
londonZone_stkatherinesdock.png|londonzone_stkatherinesdock.png|Replaced by revised St Katharine's Dock image
londonZone_trentpark.png|londonzone_trentpark.png|Replaced by revised Trent Park image
mazeZone_mazehub.png|maze_hub.png|Replaced by revised Maze hub image
newYorkZone_aevirawarehouse.png|newyork_aevirawarehouse.png|Replaced by revised Aevira Warehouse image
newYorkZone_burgerjoint.png|newyork_burger_joint.png|Replaced by revised Burger Joint image
newYorkZone_centralpark.png|newyork_centralpark.png|Replaced by revised Central Park image
newYorkZone_greasystoreroom.png|newyork_greasystoreroom.png|Replaced by revised Greasy Store Room image
newYorkZone_newyorkhub.png|newyork_hub.png|Replaced by revised New York hub image
MAP
)

echo "# Archived Replaced Room Images" > "$MANIFEST"
echo >> "$MANIFEST"
echo "Generated by \`archive-replaced-room-images.sh\`." >> "$MANIFEST"
echo >> "$MANIFEST"
echo "Dry run: \`$DRY_RUN\`" >> "$MANIFEST"
echo >> "$MANIFEST"
echo "| Action | Old image | Replacement image | Referenced in repo? | Reason |" >> "$MANIFEST"
echo "|---|---|---|---|---|" >> "$MANIFEST"

echo
echo "Archive target:"
echo "  $ARCHIVE"
echo

moved=0
skipped=0
missing=0
referenced=0

while IFS='|' read -r old new reason; do
  [ -z "${old:-}" ] && continue

  old_path="$IMG/$old"
  new_path="$IMG/$new"

  if [ ! -f "$old_path" ]; then
    echo "MISSING old image: $old"
    echo "| missing | \`$old\` | \`$new\` | n/a | $reason |" >> "$MANIFEST"
    missing=$((missing + 1))
    continue
  fi

  if [ ! -f "$new_path" ]; then
    echo "SKIP: replacement not found for $old -> $new"
    echo "| skipped; replacement missing | \`$old\` | \`$new\` | n/a | $reason |" >> "$MANIFEST"
    skipped=$((skipped + 1))
    continue
  fi

  # Check whether the old filename is still referenced outside public/images archive.
  refs="$(grep -RIl \
    --exclude-dir=.git \
    --exclude-dir=node_modules \
    --exclude-dir=dist \
    --exclude-dir=.restore-test \
    --exclude-dir=_archive \
    --exclude=archive-replaced-room-images.sh \
    --exclude=ARCHIVED_REPLACED_ROOM_IMAGES.md \
    --exclude=ROOM_IMAGE_TRACKER.csv \
    --exclude=ROOM_IMAGE_TRACKER.md \
    "$old" \
    "$REPO/src" "$REPO/docs" 2>/dev/null || true)"

  if [ -n "$refs" ]; then
    echo
    echo "REFERENCED: $old"
    echo "$refs" | sed 's/^/  /'
    echo "| skipped; still referenced | \`$old\` | \`$new\` | yes | $reason |" >> "$MANIFEST"
    referenced=$((referenced + 1))
    continue
  fi

  echo "ARCHIVE: $old -> _archive/replaced-by-revised-room-images/$old"
  echo "| archived | \`$old\` | \`$new\` | no | $reason |" >> "$MANIFEST"

  if [ "$DRY_RUN" != "1" ]; then
    mv "$old_path" "$ARCHIVE/$old"
  fi

  moved=$((moved + 1))

done <<< "$REPLACEMENTS"

echo
echo "Summary:"
echo "  Archive candidates: $moved"
echo "  Skipped:            $skipped"
echo "  Still referenced:   $referenced"
echo "  Missing old files:  $missing"
echo
echo "Manifest:"
echo "  $MANIFEST"

if [ "$DRY_RUN" = "1" ]; then
  echo
  echo "This was a dry run. To actually archive, run:"
  echo "  DRY_RUN=0 ./archive-replaced-room-images.sh"
fi

echo
echo "Git status:"
git status --short public/images docs/visuals
