#!/usr/bin/env bash
set -euo pipefail

SRC="$HOME/Documents/Development/new-images"
REPO="$HOME/Documents/Development/Gorstan"
DEST="$REPO/public/images"
TRACK_DIR="$REPO/docs/visuals"
TRACK_CSV="$TRACK_DIR/ROOM_IMAGE_PROGRESS.csv"
TRACK_MD="$TRACK_DIR/ROOM_IMAGE_PROGRESS.md"

mkdir -p "$DEST" "$TRACK_DIR"

if [ ! -d "$SRC" ]; then
  echo "ERROR: Source directory not found: $SRC"
  exit 1
fi

if [ ! -d "$REPO/.git" ]; then
  echo "ERROR: Gorstan repo not found at: $REPO"
  exit 1
fi

# source|canonical destination|room label|status
ROOMS=$(cat <<'MAP'
elfhame_eastwoods.png|elfhame_eastwoods.png|Elfhame East Woods|todo
elfhame_hub.png|elfhame_hub.png|Elfhame Hub|todo
elfhame_palace.png|elfhame_palace.png|Elfhame Palace|todo
elfhame_woods.png|elfhame_woods.png|Elfhame Woods|todo
elhame_lake.png|elhame_lake.png|Elhame Lake|todo
glitch_hub.png|glitch_hub.png|Glitch Hub|todo
gorstan_carron.png|gorstan_carron.png|Gorstan Carron|todo
gorstan_carronspire.png|gorstan_carronspire.png|Gorstan Carron Spire|todo
gorstan_hub.png|gorstan_hub.png|Gorstan Hub|todo
gorstan_torridon.png|gorstan_torridon.png|Gorstan Torridon|todo
gorstan_torridon_inn.png|gorstan_torridon_inn.png|Gorstan Torridon Inn|todo
gorstan_torridon_ruined.png|gorstan_torridon_ruined.png|Gorstan Torridon Ruined|todo
intro_controlnexus.png|introzone_controlnexus.png|Control Nexus|done
intro_controlroom.png|introzone_controlroom.png|Control Room|done
intro_introreset.png|introzone_introreset.png|Intro Reset|todo
lattice_hub.png|lattice_hub.png|Lattice Hub|todo
london_dalesapartment.png|londonzone_dalesapartment.png|Dale's Apartment|done
london_findlaterscafe.png|londonzone_findlaters.png|Findlater's Café|done
london_stkatherinesdock.png|londonzone_stkatherinesdock.png|St Katharine's Dock|todo
london_trentpark.png|londonzone_trentpark.png|Trent Park|todo
maze_hub.png|maze_hub.png|Maze Hub|todo
newyork_aevirawarehouse.png|newyork_aevirawarehouse.png|Aevira Warehouse|todo
newyork_burger_joint.png|newyork_burger_joint.png|Burger Joint|todo
newyork_centralpark.png|newyork_centralpark.png|Central Park|todo
newyork_greasystoreroom.png|newyork_greasystoreroom.png|Greasy Store Room|todo
newyork_hub.png|newyork_hub.png|New York Hub|todo
MAP
)

echo "Copying new room images into $DEST"
echo

printf "room_label,source_file,canonical_file,source_present,copied,status,notes\n" > "$TRACK_CSV"

copied_count=0
missing_count=0

while IFS='|' read -r src_file dest_file room_label status; do
  [ -z "${src_file:-}" ] && continue

  src_path="$SRC/$src_file"
  dest_path="$DEST/$dest_file"

  if [ -f "$src_path" ]; then
    cp -f "$src_path" "$dest_path"
    copied="yes"
    present="yes"
    notes="copied from new-images"
    copied_count=$((copied_count + 1))
    echo "OK: $src_file -> public/images/$dest_file"
  else
    copied="no"
    present="no"
    notes="source image missing from new-images"
    missing_count=$((missing_count + 1))
    echo "MISSING: $src_file"
  fi

  printf '"%s","%s","%s","%s","%s","%s","%s"\n' \
    "$room_label" "$src_file" "$dest_file" "$present" "$copied" "$status" "$notes" >> "$TRACK_CSV"

done <<< "$ROOMS"

cat > "$TRACK_MD" <<EOFMD
# Gorstan Room Image Progress

Generated by \`sync-new-room-images.sh\`.

Source directory:

\`\`\`text
$SRC
\`\`\`

Destination directory:

\`\`\`text
public/images
\`\`\`

## Current implementation status

\`done\` means the room is already part of the current visual-room conversion path or has been used/expected in the active slice.

\`todo\` means the image has been copied into the repo but still needs room metadata/hotspots/parser-equivalence work before it is a playable visual room.

| Status | Room | Source image | Canon game image |
|---|---|---|---|
EOFMD

while IFS='|' read -r src_file dest_file room_label status; do
  [ -z "${src_file:-}" ] && continue
  echo "| $status | $room_label | \`$src_file\` | \`public/images/$dest_file\` |" >> "$TRACK_MD"
done <<< "$ROOMS"

cat >> "$TRACK_MD" <<'EOFMD'

## Already completed / active visual path

- Findlater's Café / Coffee Shop
- Dale's Apartment
- Control Nexus recommended as the next major visual room after Café + Dale playtest

## Still to convert into playable visual rooms

The image existing in `public/images` is only step one. Each room still needs, where applicable:

- `visualScene` metadata
- hotspot map
- click-to-`COMMAND_INPUT` routing
- typed/clicked command equivalence tests
- useful examine/talk/move feedback
- ACTIVE_REPO_MAP update

EOFMD

echo
echo "Copied images:  $copied_count"
echo "Missing images: $missing_count"
echo
echo "Wrote:"
echo "  $TRACK_CSV"
echo "  $TRACK_MD"
echo
echo "Git status:"
git status --short public/images docs/visuals sync-new-room-images.sh
