// Centralized content for the Rabbit Trial Arc.
// NOTE: Paste the provided FULL RABBIT SEQUENCE here (verbatim).
// You may include optional pause markers: [pause:micro|short|medium|long|<ms>]

export const POST_NY_RABBIT_CLEARING_ID = 'POST_NY_RABBIT_CLEARING' as const;
export const RABBIT_TRIAL_01_GATE_ID = 'RABBIT_TRIAL_01_GATE' as const;

export const TRIAL_MOUNTAIN_DESCENT_ID = 'TRIAL_MOUNTAIN_DESCENT' as const;
export const TRIAL_GOLEM_PASS_ID = 'TRIAL_GOLEM_PASS' as const;
export const TRIAL_VILLAGE_ID = 'TRIAL_VILLAGE' as const;

export const RABBIT_CUTSCENE_LINES: readonly string[] = [
  '[pause:short]',
  'The clearing is quiet in a way that suggests planning.',
  '[pause:medium]',
  '',
  'A purple rabbit stands where there was nothing a moment ago.',
  '[pause:short]',
  '',
  'Its fur absorbs the light rather than reflecting it.',
  '[pause:short]',
  '',
  'Its eyes are black.',
  '[pause:micro]',
  'Not dark.',
  '[pause:micro]',
  'Black.',
  '[pause:short]',
  '',
  'They do not blink.',
  '[pause:short]',
  '',
  'You have the impression it is not looking at you so much as',
  '[pause:micro]',
  'accounting for you.',
  '[pause:medium]',
  '',
  '“We were going to challenge Cora.”',
  '[pause:medium]',
  '',
  'The rabbit looks past you.',
  '[pause:micro]',
  'Briefly.',
  '[pause:short]',
  '',
  '“She isn’t here.”',
  '[pause:medium]',
  '',
  '“So we chose you instead.”',
  '[pause:medium]',
  '',
  'The rabbit’s ears tilt slightly.',
  '[pause:micro]',
  'This may be apology.',
  '[pause:micro]',
  'It may be logistics.',
  '[pause:medium]',
  '',
  '“Not because you are ideal.”',
  '[pause:short]',
  '',
  '“Because you are available.”',
  '[pause:long]',
  '',
  '“The task remains the same.”',
  '[pause:medium]',
  '',
  '“An artefact was taken into the high paths.”',
  '[pause:short]',
  '',
  '“It must be retrieved.”',
  '[pause:medium]',
  '',
  '“The route will test what you avoid,”',
  '[pause:micro]',
  '“what you rush,”',
  '[pause:micro]',
  '“and what you listen to.”',
  '[pause:medium]',
  '',
  'The rabbit finally looks directly at you.',
  '[pause:medium]',
  '',
  '“If you succeed,”',
  '[pause:micro]',
  '“a door will open.”',
  '[pause:medium]',
  '',
  '“If you fail—”',
  '[pause:long]',
  '',
  'The rabbit stops.',
  '[pause:micro]',
  'Considers you.',
  '[pause:medium]',
  '',
  '“Then we will have to choose again.”',
  '[pause:long]',
  '',
  'The ground ahead shifts.',
  '[pause:short]',
  '',
  'A path reveals itself,',
  '[pause:micro]',
  'narrow,',
  '[pause:micro]',
  'unforgiving.',
  '[pause:medium]',
  '',
  'The rabbit is already gone.',
  '[pause:long]',
];
