/*
  Gorstan – Interactive Game Framework
  Copyright © 2025 Geoff Webster. All Rights Reserved.

  This source code is proprietary and confidential.
  Unauthorised copying, distribution, modification, resale,
  reverse engineering, or use of this file, via any medium,
  is strictly prohibited without prior written consent
  from the copyright holder.

  Licensed access is granted only to authorised users who have
  purchased access to Gorstan through official channels.
  Such licence is strictly limited to running and playing the
  Gorstan game. No part of this source code may be used to
  create derivative works, other games, or redistributed in
  any form.

  Third-party libraries and assets are included under their
  respective licences as detailed in package.json and assets/.
*/

// RSLoreUnlockListener.tsx – Listens for Rune Sprint chamber solve events and shows lore unlock toasts
import React, { useEffect, useState } from 'react';
import { Toast } from '../../components/ui';
import { awardFragments } from '../features/RS_LoreRegister';

interface ActiveToast { id: string; msg: string; kind: 'lore' | 'fragments'; }

// Utility: push a toast object with autogenerated id
function makeToast(msg: string, kind: ActiveToast['kind']): ActiveToast { return { id: `${kind}-${Math.random().toString(36).slice(2)}`, msg, kind }; }

export const RSLoreUnlockListener: React.FC = () => {
  const [toasts, setToasts] = useState<ActiveToast[]>([]);

  useEffect(() => {
    const onChamberSolved = (e: Event) => {
      const detail = (e as CustomEvent).detail || {};
      const fragments = typeof detail.fragments === 'number' ? detail.fragments : 1;
      const { newlyUnlocked, total } = awardFragments(fragments);
      setToasts(prev => [makeToast(`Fragments +${fragments} (Total ${total})`, 'fragments'), ...prev]);
      newlyUnlocked.forEach(entry => {
        setToasts(prev => [makeToast(entry.title + ' unlocked', 'lore'), ...prev]);
        // Also emit a separate descriptive toast
        setToasts(prev => [makeToast(`[REGISTER] ${entry.title}: ${entry.body}`, 'lore'), ...prev]);
      });
    };
    document.addEventListener('rs:chamber-solved', onChamberSolved as any);
    const onLoreUnlock = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      if (detail?.message) setToasts(prev => [makeToast(detail.message, 'lore'), ...prev]);
    };
    document.addEventListener('rs:lore-unlock', onLoreUnlock as any);
    return () => {
      document.removeEventListener('rs:chamber-solved', onChamberSolved as any);
      document.removeEventListener('rs:lore-unlock', onLoreUnlock as any);
    };
  }, []);

  const dismiss = (id: string) => setToasts(prev => prev.filter(t => t.id !== id));

  if (!toasts.length) return null;

  return (
    <div className="fixed top-4 right-4 z-[1080] flex flex-col gap-2 w-[300px]">
      {toasts.map(t => (
        <Toast
          key={t.id}
          id={t.id}
            // map kind to toast variants; lore=info, fragments=success
          type={t.kind === 'fragments' ? 'success' : 'info'}
          message={<span className="text-xs leading-snug">{t.msg}</span>}
          duration={4500}
          dismissible
          onDismiss={dismiss}
        />
      ))}
    </div>
  );
};

export default RSLoreUnlockListener;
